name: Build

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: windows
            os: windows-latest
            artifact_name: target/release/dominos-coupons.exe
            asset_name: dominos-coupons-win
          - name: macos
            os: macos-latest
            artifact_name: target/release/dominos-coupons
            asset_name: dominos-coupons-mac

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --locked

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
